#ifndef ERROR_CODE_PKQUE_H_
#define ERROR_CODE_PKQUE_H_

#ifndef EC_PKQUE_BASENO
#define EC_PKQUE_BASENO					13000 // iCV5公共错误代码起始
#define EC_PKQUE_INITFAILED				EC_PKQUE_BASENO + 10			// PKSOCK初始化失败
#define EC_PKQUE_LISTENFAILED				EC_PKQUE_BASENO + 11			// PKSOCK监听端口失败
#define EC_PKQUE_SENDFAILED				EC_PKQUE_BASENO + 12			// 发送数据失败
#define EC_PKQUE_RECVFAILED				EC_PKQUE_BASENO + 13			// 接收数据失败
#define EC_PKQUE_FINALIZEFAILED			EC_PKQUE_BASENO + 14			// 终止CVNDK服务失败
#define EC_PKQUE_QUEUEERROR				EC_PKQUE_BASENO + 15			// PKSOCK中的Queue相关错误
#define EC_PKQUE_CONNECTFAILED				EC_PKQUE_BASENO + 16			// 连接失败
#define EC_PKSOCKK_GET_PORT_FAILED			EC_PKQUE_BASENO + 17			// 获取指定应用的端口失败
#define EC_PKQUE_RECV_TIMEOUT				EC_PKQUE_BASENO + 18			// 接收数据超时
#define EC_PKQUE_NOT_INIT					EC_PKQUE_BASENO + 19			// PKSOCK尚未初始化
#define EC_PKQUE_INVALID_PARAMETER			EC_PKQUE_BASENO + 20			// 无效的参数传递
#define EC_PKQUE_MALLOC_FAILED				EC_PKQUE_BASENO + 21			// 分配空间失败
#define EC_PKQUE_PUTQ_FAILED				EC_PKQUE_BASENO + 22			// 数据发送到全局写Queue失败
#define EC_PKQUE_LOCAL_QUEUE_NOT_FOUND		EC_PKQUE_BASENO + 23			// 本地Queue未查找到
#define EC_PKQUE_CONNECT_NOT_EXIST			EC_PKQUE_BASENO + 24			// 与远端Queue的连接不存在
#define EC_PKQUE_ACQUIRE_MUTEX_FAILED		EC_PKQUE_BASENO + 25			// 获取全局锁失败
#endif // #ifndef EC_PKQUE_COMM_BASENO

#endif//ERROR_CODE_CVNDK_H_
