/**************************************************************
 *  Filename:    common_sqlapiwrapper.h
 *  Copyright:   Shanghai Peak InfoTech Co., Ltd.
 *
 *  Description: 主要记录错误码和一般定义
 *
 *  @author:     zhangqiang
 *  @version     10/26/2012  zhangqiang  Initial Version
**************************************************************/
//SQLAPIWRAPPER中错误码定义
#define ICV_SUCCESS 							0
#define EC_ICV_ZT_SQLAPIWRAPPER_BASE					17000
#define EC_ICV_ZT_SQLAPIWRAPPER_CONNECTDBFAILED   	EC_ICV_ZT_SQLAPIWRAPPER_BASE + 1
#define EC_ICV_ZT_SQLAPIWRAPPER_DISCONNECTDBFAILED   EC_ICV_ZT_SQLAPIWRAPPER_BASE + 2
#define EC_ICV_ZT_SQLAPIWRAPPER_CONNECTIDNOTEXIST	EC_ICV_ZT_SQLAPIWRAPPER_BASE + 3
#define EC_ICV_ZT_SQLAPIWRAPPER_QUERYDATAFAILED		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 4
#define EC_ICV_ZT_SQLAPIWRAPPER_QUERYNOTEXIST		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 5
#define EC_ICV_ZT_SQLAPIWRAPPER_RESULTNOTEXIST		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 6
#define EC_ICV_ZT_SQLAPIWRAPPER_GETRECORDFAILED		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 7
#define EC_ICV_ZT_SQLAPIWRAPPER_INSERTFAILED			EC_ICV_ZT_SQLAPIWRAPPER_BASE + 8
#define EC_ICV_ZT_SQLAPIWRAPPER_BINDNAMEERROR		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 9
#define EC_ICV_ZT_SQLAPIWRAPPER_UPDATEFAILED			EC_ICV_ZT_SQLAPIWRAPPER_BASE + 10
#define EC_ICV_ZT_SQLAPIWRAPPER_DELETEFAILED			EC_ICV_ZT_SQLAPIWRAPPER_BASE + 11
#define EC_ICV_ZT_SQLAPIWRAPPER_EXECSQLFAILED		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 12
#define EC_ICV_ZT_SQLAPIWRAPPER_TRANSACTFAILED		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 13
#define EC_ICV_ZT_SQLAPIWRAPPER_COMMITFAILED			EC_ICV_ZT_SQLAPIWRAPPER_BASE + 14
#define EC_ICV_ZT_SQLAPIWRAPPER_ROLLBACKFAILED		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 15
#define EC_ICV_ZT_SQLAPIWRAPPER_BINDNAMENOTEXIST		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 16
#define EC_ICV_ZT_SQLAPIWRAPPER_SQLGETVALUEBYINDEXFAILED		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 17
#define EC_ICV_ZT_SQLAPIWRAPPER_SQLGETVALUEBYFIELDFAILED		EC_ICV_ZT_SQLAPIWRAPPER_BASE + 18

#define EC_ICV_SQLAPIWRAPPER_BASE					EC_ICV_ZT_SQLAPIWRAPPER_BASE
#define EC_ICV_SQLAPIWRAPPER_CONNECTDBFAILED   	EC_ICV_ZT_SQLAPIWRAPPER_CONNECTDBFAILED
#define EC_ICV_SQLAPIWRAPPER_DISCONNECTDBFAILED   EC_ICV_ZT_SQLAPIWRAPPER_DISCONNECTDBFAILED
#define EC_ICV_SQLAPIWRAPPER_CONNECTIDNOTEXIST	EC_ICV_ZT_SQLAPIWRAPPER_CONNECTIDNOTEXIST
#define EC_ICV_SQLAPIWRAPPER_QUERYDATAFAILED		EC_ICV_ZT_SQLAPIWRAPPER_QUERYDATAFAILED
#define EC_ICV_SQLAPIWRAPPER_QUERYNOTEXIST		EC_ICV_ZT_SQLAPIWRAPPER_QUERYNOTEXIST
#define EC_ICV_SQLAPIWRAPPER_RESULTNOTEXIST		EC_ICV_ZT_SQLAPIWRAPPER_RESULTNOTEXIST
#define EC_ICV_SQLAPIWRAPPER_GETRECORDFAILED		EC_ICV_ZT_SQLAPIWRAPPER_GETRECORDFAILED
#define EC_ICV_SQLAPIWRAPPER_INSERTFAILED			EC_ICV_ZT_SQLAPIWRAPPER_INSERTFAILED
#define EC_ICV_SQLAPIWRAPPER_BINDNAMEERROR		EC_ICV_ZT_SQLAPIWRAPPER_BINDNAMEERROR
#define EC_ICV_SQLAPIWRAPPER_UPDATEFAILED			EC_ICV_ZT_SQLAPIWRAPPER_UPDATEFAILED
#define EC_ICV_SQLAPIWRAPPER_DELETEFAILED			EC_ICV_ZT_SQLAPIWRAPPER_DELETEFAILED
#define EC_ICV_SQLAPIWRAPPER_EXECSQLFAILED		EC_ICV_ZT_SQLAPIWRAPPER_EXECSQLFAILED
#define EC_ICV_SQLAPIWRAPPER_TRANSACTFAILED		EC_ICV_ZT_SQLAPIWRAPPER_TRANSACTFAILED
#define EC_ICV_SQLAPIWRAPPER_COMMITFAILED			EC_ICV_ZT_SQLAPIWRAPPER_COMMITFAILED
#define EC_ICV_SQLAPIWRAPPER_ROLLBACKFAILED		EC_ICV_ZT_SQLAPIWRAPPER_ROLLBACKFAILED
#define EC_ICV_SQLAPIWRAPPER_BINDNAMENOTEXIST		EC_ICV_ZT_SQLAPIWRAPPER_BINDNAMENOTEXIST
#define EC_ICV_SQLAPIWRAPPER_SQLGETVALUEBYINDEXFAILED		EC_ICV_ZT_SQLAPIWRAPPER_SQLGETVALUEBYINDEXFAILED
#define EC_ICV_SQLAPIWRAPPER_SQLGETVALUEBYFIELDFAILED		EC_ICV_ZT_SQLAPIWRAPPER_SQLGETVALUEBYFIELDFAILED
//DBPROXYAPI中错误码定义
#define EC_ICV_DBPROXY_INVALIDPARAM                  17100
#define EC_ICV_DBPROXY_XMLRESPONSEERROR              17101 
//DBProxyservice中错误码定义
#define EC_ICV_DBProxy_XMLRESPONSEERROR          17200
#define EC_ICV_DBProxy_FAILTOSTARTTASK           17201 
#define EC_ICV_DBProxy_FAILTOREGLOCALQUE         17202
#define EC_ICV_DBProxy_CONNECTERROR              17203
#define EC_ICV_DBProxy_DISCONNECTERROR           17204
#define EC_ICV_DBProxy_SELECTERROR               17205
#define EC_ICV_DBProxy_FIRSTERROR                17206
#define EC_ICV_DBProxy_LASTERROR                 17207
#define EC_ICV_DBProxy_NEXTERROR                 17208
#define EC_ICV_DBProxy_PREVERROR                 17209
#define EC_ICV_DBProxy_ENDERROR                  17210
#define EC_ICV_DBProxy_TRANSACTERROR             17211
#define EC_ICV_DBProxy_COMMITERROR               17212
#define EC_ICV_DBProxy_ROLLBACKERROR             17213
#define EC_ICV_DBProxy_EXCUTEERROR               17214
#define EC_ICV_DBProxy_GETRECORDERROR            17215
#define EC_ICV_DBProxy_NUMROWSERROR              17216
#define EC_ICV_DBProxy_GETVALUEBYFIELDERROR      17217
#define EC_ICV_DBProxy_GETVALUEBYINDEXERROR      17218

#define TAG_VALUE_LEN			2048 // 读写TAG点时值的长度
#define SQL_MAX_LENGTH				1024
#define SQLAPI_SCROLLABLE_CURSOR

#define SQLAPI_SCROLLABLE_CURSOR


#define DBPROXYAPI_LOGFILE	"dbproxyapi" // 通信模块日志文件名称
//tinyXml 通信报文中关键字定义
#define REQUEST_OBJECTNAME_CONNECTIONID "CONNECTIONID"
#define REQUEST_OBJECTNAME_CONNECTIONSTRING "CONNECTIONSTRING"
#define REQUEST_OBJECTNAME_USERNAME "USERNAME"
#define REQUEST_OBJECTNAME_PASSWORD "PASSWORD"
#define REQUEST_OBJECTNAME_DATABASETYPE "DATABASETYPE"
#define REQUEST_OBJECTNAME_TIMEOUT "TIMEOUT"
#define REQUEST_OBJECTNAME_CODINGSET "CODINGSET"
//#define REQUEST_OBJECTNAME_TABLENAME "TABLENAME"
//#define REQUEST_OBJECTNAME_BINDLIST "BINDLIST"
//#define REQUEST_OBJECTNAME_WHEREEXPR "WHEREEXPR"
//#define REQUEST_OBJECTNAME_ORDERBYEXPRESSION "ORDERBYEXPRESSION"
#define REQUEST_OBJECTNAME_SQLEXPRESSION "SQLEXPRESSION"
#define REQUEST_OBJECTNAME_RECORDNUMBER "RECORDNUMBER"
#define REQUEST_OBJECTNAME_QUERYID "QUERYID"
#define REQUEST_OBJECTNAME_FIELDNAME "FIELDNAME"
#define REQUEST_OBJECTNAME_FIELDINDEX "FIELDINDEX"
#define REQUEST_OBJECTNAME_NUMROWS "NUMROWS"

#define REQUEST_OBJECTNAME_FIELD "FIELD"
#define REQUEST_OBJECTNAME_FIELDVALUE "FIELDVALUE"


/****************************************************
请求类型
****************************************************/
#define REQUEST_OPERATETYPE_CONNECT		"SQLConnectEx"
#define REQUEST_OPERATETYPE_DISCONNECT		"SQLDisconnect"
#define REQUEST_OPERATETYPE_CONNECTTEST		"SQLConnectTestEx"
#define REQUEST_OPERATETYPE_SQLSELECTBYSQL		"SQLSelectBySQL"
#define REQUEST_OPERATETYPE_SQLGETRECORD		"SQLGetRecord"
#define REQUEST_OPERATETYPE_SQLNUMROWS		"SQLNumRows"
#define REQUEST_OPERATETYPE_SQLFIRST		"SQLFirst"
#define REQUEST_OPERATETYPE_SQLNEXT		"SQLNext"
#define REQUEST_OPERATETYPE_SQLPREV		"SQLPrev"
#define REQUEST_OPERATETYPE_SQLLAST		"SQLLast"
#define REQUEST_OPERATETYPE_SQLEND		"SQLEnd"
#define REQUEST_OPERATETYPE_SQLEXECUTE		"SQLExecute"
#define REQUEST_OPERATETYPE_SQLTRANSACT		"SQLTransact"
#define REQUEST_OPERATETYPE_SQLCOMMIT		"SQLCommit"
#define REQUEST_OPERATETYPE_SQLROLLBACK		"SQLRollback"
//#define REQUEST_OPERATETYPE_UNINITIALIZE		"UnInitialize"
#define REQUEST_OPERATETYPE_SQLGETVALUEBYFIELD		"SQLGetValueByField"
#define REQUEST_OPERATETYPE_SQLGETVALUEBYINDEX		"SQLGetValueByIndex"


#define RESPONSE_ATTRNAME_ERRORNO "ERRORNO"
#define RESPONSE_ATTRNAME_ERRORTEXT "ERRORTEXT"



// macro to convert info stored in XMLParser to string(char *)
#define XMLParser2String(_CCXMLPARSER_) TiXmlPrinter printer; \
	printer.SetIndent("\t"); \
	_CCXMLPARSER_.Accept( &printer ); \
char * szXMLContent = (char *)printer.CStr();


#define CDBPROXY_SERVICE_QUEID	191
#define CDBPROXY_CLIENT_QUEID	190


#define ICV_HOSTNAMESTRING_MAXLEN		64  // 主机名称的最大程度
#define EC_ICV_CC_IPINVALID 							11205 // IP地址非法