#ifndef ERROR_CODE_PKSOCK_H_
#define ERROR_CODE_PKSOCK_H_

#ifndef EC_PKSOCK_BASENO
#define EC_PKSOCK_BASENO					13000 // iCV5公共错误代码起始
#define EC_PKSOCK_INITFAILED				EC_PKSOCK_BASENO + 10			// PKSOCK初始化失败
#define EC_PKSOCK_LISTENFAILED				EC_PKSOCK_BASENO + 11			// PKSOCK监听端口失败
#define EC_PKSOCK_SENDFAILED				EC_PKSOCK_BASENO + 12			// 发送数据失败
#define EC_PKSOCK_RECVFAILED				EC_PKSOCK_BASENO + 13			// 接收数据失败
#define EC_PKSOCK_FINALIZEFAILED			EC_PKSOCK_BASENO + 14			// 终止CVNDK服务失败
#define EC_PKSOCK_QUEUEERROR				EC_PKSOCK_BASENO + 15			// PKSOCK中的Queue相关错误
#define EC_PKSOCK_CONNECTFAILED				EC_PKSOCK_BASENO + 16			// 连接失败
#define EC_PKSOCKK_GET_PORT_FAILED			EC_PKSOCK_BASENO + 17			// 获取指定应用的端口失败
#define EC_PKSOCK_RECV_TIMEOUT				EC_PKSOCK_BASENO + 18			// 接收数据超时
#define EC_PKSOCK_NOT_INIT					EC_PKSOCK_BASENO + 19			// PKSOCK尚未初始化
#define EC_PKSOCK_INVALID_PARAMETER			EC_PKSOCK_BASENO + 20			// 无效的参数传递
#define EC_PKSOCK_MALLOC_FAILED				EC_PKSOCK_BASENO + 21			// 分配空间失败
#define EC_PKSOCK_PUTQ_FAILED				EC_PKSOCK_BASENO + 22			// 数据发送到全局写Queue失败
#define EC_PKSOCK_LOCAL_QUEUE_NOT_FOUND		EC_PKSOCK_BASENO + 23			// 本地Queue未查找到
#define EC_PKSOCK_CONNECT_NOT_EXIST			EC_PKSOCK_BASENO + 24			// 与远端Queue的连接不存在
#define EC_PKSOCK_ACQUIRE_MUTEX_FAILED		EC_PKSOCK_BASENO + 25			// 获取全局锁失败
#endif // #ifndef EC_PKSOCK_COMM_BASENO

#endif//ERROR_CODE_CVNDK_H_
