#ifndef ERROR_CODE_CVNDK_H_
#define ERROR_CODE_CVNDK_H_

#define EC_ICV_SHMQUEUE_FAILTO_ALLOCMEMORY  				13009 // 分配内存失败
#define EC_ICV_SHMQUEUE_INVALID_PARAM   				13039 // 传入参数非法
#define EC_ICV_BDBQUEUE_OPEN_DB_FILE_FAILED 			13040 // 打开文件失败
#define EC_ICV_BDBQUEUE_DB_NOT_INITIALIZED  			13041 // 文件未打开
#define EC_ICV_BDBQUEUE_NOT_FOUND   					13042 // 文件未找到
#define EC_ICV_BDBQUEUE_BUFFER_TOO_LONG 				13043 // 插入过长的Buffer
#define EC_ICV_BDBQUEUE_DB_IO_ERROR 					13044 // 读写DB时异常

#define EC_ICV_SHMQUEUE_ACQUIRE_MUTEX_FAILED			13045 // 获取锁失败
#define EC_ICV_SHMQUEUE_MALLOC_MMAP_FAILED  			13046 // 分配共享内存失败
#define EC_ICV_SHMQUEUE_WAKEDUP 						13047 // 队列强制唤醒
#define EC_ICV_SHMQUEUE_QUEUE_INFO_MISMATCH 			13048 // 队列信息不匹配
#define EC_ICV_SHMQUEUE_CALL_BACK_FAILED				13049 // 调用CallBack方法异常

#endif//ERROR_CODE_CVNDK_H_
